modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/cech12/WoodenBucket/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="woodenbucket"
    version="${file.jarVersion}"
    displayName="Wooden Bucket"
    displayURL="https://github.com/cech12/WoodenBucket"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds a Wooden Bucket.
    '''
[[dependencies.woodenbucket]]
    modId="forge"
    mandatory=true
    versionRange="[44.0.41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.woodenbucket]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.woodenbucket]]
    modId="bucketlib"
    mandatory=true
    versionRange="[1.19.3-1.1.0.0,)"
    referralUrl="https://github.com/cech12/BucketLib"
    ordering="NONE"
    side="BOTH"