modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/cech12/WoodenBucket/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="woodenbucket"
    version="${file.jarVersion}"
    displayName="Wooden Bucket"
    displayURL="https://github.com/cech12/WoodenBucket"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds a Wooden Bucket.
    '''
[[dependencies.woodenbucket]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.18,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.woodenbucket]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.woodenbucket]]
    modId="bucketlib"
    mandatory=true
    versionRange="[1.18.2-0.5.3.2,)"
    ordering="NONE"
    side="BOTH"